### ISSUE TITLE
Namadillo: Speed up Shielded-sync by adapting block bundle size to height

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada-interface#1420]
It takes about 12 seconds to `shielded-sync` from height 0 to 140,000 in the CLI, and about 1.5 minute in Namadillo, both using the MASP indexer with HTTP/2 enabled.

To reduce web worker serialization overhead, Namadillo requests blocks in bundles of 30, which adds up to 5800 bundles at this height. 

To speed up `shielded-sync`, the block bundle size could dynamically adapt to the height difference, to switch to bundles of for example 10,000, 1,000 and 30 blocks.

![image](https://github.com/user-attachments/assets/268de3bd-1c19-4e30-a097-03aca83c6c40)

**Comment by mateuszjasiuk** [comment]
Hello, I think  the problem is that CLI is using 100 concurrent fetches and we use 10.
https://github.com/anoma/namada-interface/pull/1441 should fix that and more :)
but I like the idea of dynamically setting batch size. We can do it after phase 3 I think.

btw:
with batch size 100 and 100 concurrent fetches we get 185k blocks in 15sec which seems to be faster than cli :)

**Comment by Rigorously** [comment]
Nice speedup! I thought the CPU was the bottleneck because of the browser overhead processing small bundles.
