### ISSUE TITLE
Balance isn't automatically update when receiving token

### ISSUE THREAD

**Issue by kyrtill6b** [anoma/namada-interface#706]
Issue:
- When another account transfer token, the application namada-interface is not update automatically update the balances. Only reload the page manually to reload balance

**Comment by emccorson** [comment]
Just to clarify, the problem is that when an account receives tokens from a transfer, the interface does not update? If that's the case, that is not currently supported by the interface.

I'm not sure whether we will choose to support this feature. We would need to investigate the technical difficulty of having something like that. I will mark this as PoC/maybe for now.

**Comment by kyrtill6b** [comment]
Hi @emccorson, thank you for your quick response. Yes the issue is that when an account receives tokens from a transfer, the interface does not update. In my opinion, the application should have this feature like another wallet (For example: Metamask, Kelpr,...). This feature helps enhance user experience when they use the application.

**Comment by pnam1609** [comment]
In my view, this feature is indispensable for the functionality of this application. 
I looked at [707](https://github.com/anoma/namada-interface/pull/707) and this solution works as described. It's worth noting that it used the Cosmos SDK library to implement this, which will trigger query balancing when a new block change occurs. I wonder if there is any library that supports only catching the event when receiving the token instead of catching all changes of the event block. It makes for better performance. However, [707](https://github.com/anoma/namada-interface/pull/707) still is a good contribution.

**Comment by pedrorezende** [comment]
@pnam1609 thanks for the contribution! Just a quick update: we're going to revisit this PR on phase 3. You can check the suggested phases for Namada [here](https://namada.net/mainnet-launch)
