### ISSUE TITLE
Extension Architecture

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#85]
# Description
This is a follow-up task for collecting changes for the extension.

**Comment by memasdeligeorgakis** [comment]
See this https://github.com/anoma/namada-interface/pull/48#issuecomment-1256425783 comment for background.

**Comment by jurevans** [comment]
Comments pulled from discussion at https://github.com/anoma/namada-interface/pull/48#issuecomment-1256425783

I see this application containing 3 primary components:

1. The **background** services (we can think of this as a back-end API that the extension pages/scripts can interact with) running in the service worker/background scripts - this can access storage, call wasm functions, sign transactions, etc.
2. The **injected** API (This is the `InjectedAnoma` script providing the proxy to the API), which exposes public methods to the client
3. The **extension** - What I call the "extension" is everything else that can access the `WebExtension` API (outside of the background services), that has access to the browser runtime within the extension, and this has a few components:
    - The API instance in **content-scripts** (responsible for injecting the proxied methods into a webpage for clients to connect to)
    - The Router responsible for relaying and validating messages between content-scripts and background
    - The React application delivered via `popup.html`, which provides access to the background services, but this could be any number of pages that exist within the extension, e.g., a post-installation setup page

Another way we could look at these components is solely by which browser/window APIs each has access to (as they'll need to be targeting these environments correctly):

| Extension Component | Global API Access|
| :-- | :-: |
| **background**  | `browser` |
| **injected**        | `window` |
| **extension**     | `browser` + `window` |
 
_Note: Manifest v2 background scripts *do* have access to the "window" API, however, as we want to target both v2 and v3 manifests from the same service, we cannot use "window". We can instead make use of the "browser" API, such as where we may want to share state between content and background, utilizing `browser.storage.local`  instead of `window.localStorage`, for example._

We should also keep in mind the build pipelines as we organize this as well, perhaps organizing around the targets to make it easy to reason about when something needs to be changed. This may make it more clear where dependencies can be shared. It's important that we're not importing unnecessary or incompatible dependencies within this project, or attempting to access an invalid API (for example, in the `page` and `content-scripts` runtime, you have both the `browser` and a limited version of the `window` APIs, but in the `background` you have no `window`, but full access to `browser` - sharing a dependency that targets `window` will crash the service worker, etc.). In this PR I've made sure that this doesn't happen, but looking at the top-level structure, it isn't clear which domain each top-level folder belongs to. 

Just for reference, these are the current Webpack targets (as of this PR) and their responsibilities - As this is ultimately what gets delivered, it may be a good idea that these are accessible from the top of the hierarchy:

- **background**
  - Service Worker (Chrome & other v3 manifests), Background Script (Firefox & other v2 manifests)
  - Responsible for key management, authentication, and interaction with the storage API
  - Is able to receive messages from an extension `page` (such as popup) or `content-scripts` via the router
  - This also has access to our wasm functionality (serializing/signing transactions, key derivation, etc.)
- **content**
  - Responsible for injecting the proxied API instance (`InjectedAnoma`)
  - Responsible for routing messages from the web page to 
- **injected**
  - The script that executes on the client's web page
- **popup**
  - The React app for managing keys
- **manifest.json**

Other projects tend to take it a step further with modularization, and many components of their extensions are actually abstracted into individual packages, perhaps for re-use in different contexts. I don't think that's important to us until we come across that use-case, but it is something to note. Just as an example, the [keplr-wallet extension](https://github.com/chainapsis/keplr-wallet/tree/master/packages) has separate packages within their mono-repo, including (but not limited to) the following:

```
packages/
  background/
  content/
  extension/
  provider/
  router/
  router-extension/
```

I've followed a somewhat similar hierarchy in parts. I like having individual services listed under `background`, with each following a similar structure from one to the next (each service should contain similarly named components within them, making it clear what their purpose is)
